### PR TITLE
Updated boost to 1.57.0

### PR DESCRIPTION
**Pull request by hezhao**
- Straight from [boost 1.57.0](http://www.boost.org/users/history/version_1_57_0.html)

### CODE REVIEW

**Comment by heisters** [comment]
+1 since this would ostensibly fix compatibility with Clang 3.4+:

https://forum.libcinder.org/topic/xcode-5-1-clang-3-4-breaks-boost
https://svn.boost.org/trac/boost/ticket/9610

**Comment by richardeakin** [comment]
I believe the plan is to wait for 1.58 to be released, which is slated for next week. By the way, we're currently using a patched version of 1.56, which has fixes for all known issues.

**Comment by heisters** [comment]
Sounds good. FYI, I was hitting the above Clang 3.4 issue on a fresh checkout of the glNext branch. It only shows up when you include certain boost headers, so it's easy to see how it was missed. I pointed my code at a fork of Cinder that merges @hezhao's update, and that fixed the issue.

**Comment by hezhao** [comment]
See [boost_1_58](https://github.com/cinder/Cinder-Boost/tree/boost_1_58) branch.

**Pull request closed without merging**
